### ISSUE TITLE
"data.map is not a function" error

### ISSUE THREAD

**Issue by SPFZ** [jigkoxsee/vscode-droneci#3] opened 2020-03-26 18:20 UTC
Hello,

I really like the idea of the plugin but I can not get it to work. After installing and entering server url + token I get a "data.map is not a function" notification when I click reload.

drone Version: current latest based on 1.6.5 (https://hub.docker.com/layers/drone/drone/latest/images/sha256-a8feba1ec4056c17e3b07ca4b83d702791759bb97a46e4a78c6be576286176e5?context=explore)
Vs code version: 1.43.2

vs code is running in WSL on Windows

Thank you for your assistance.

![image](https://user-images.githubusercontent.com/7194553/77681904-5af4ed80-6f96-11ea-8194-b751e81d2234.png)

**Comment by zikosw** [comment] 2020-03-28 08:42
Hi,
I think the problem is you didn't include HTTP(s) in the server URL.
This should be fixed in version 0.0.10.

**Comment by SPFZ** [comment] 2020-03-29 08:53
Hi,
I tried with protocol before and it was not successful. I upgraded to 0.0.10 now and get an unauthorized error. 
![image](https://user-images.githubusercontent.com/7194553/77844950-11c9b700-71ab-11ea-856a-4adaf7b2f79c.png)

The same credentials work from CLI when I copy the command from drones' account page.

**Comment by wkrause13** [comment] 2020-06-01 12:38
Has anyone found a resolution for this?

**Closed as completed** 2021-04-19 02:36 UTC
